import { ServerFile, InstalledMod } from '../types/server';

export function getDefaultServerFiles(
  serverName: string,
  port: number,
  loader: string,
  mods: InstalledMod[] = [],
  baseDir: string = '/Servers'
): ServerFile[] {
  const normalizedBase = baseDir.replace(/\/+$/, '') || '/Servers';
  const root = `${normalizedBase}/${serverName}`;
  const now = '2024-12-28 12:00:00';

  const modFiles: ServerFile[] = mods.map((m) => ({
    id: `file-mod-${m.id}`,
    name: m.filename,
    path: `${root}/mods/${m.filename}`,
    isDirectory: false,
    sizeBytes: m.fileSizeBytes,
    lastModified: '2024-12-28 10:15:00',
    extension: 'jar',
    content: undefined,
  }));

  return [
    {
      id: 'd-servers-root',
      name: normalizedBase.replace(/^\//, '') || 'Servers',
      path: normalizedBase,
      isDirectory: true,
      sizeBytes: 0,
      lastModified: now,
    },
    {
      id: `d-${serverName}`,
      name: serverName,
      path: root,
      isDirectory: true,
      sizeBytes: 0,
      lastModified: now,
    },
    {
      id: 'f-server-icon',
      name: 'server-icon.png',
      path: `${root}/server-icon.png`,
      isDirectory: false,
      sizeBytes: 1540,
      lastModified: now,
      extension: 'png',
    },
    {
      id: 'f-server-properties',
      name: 'server.properties',
      path: `${root}/server.properties`,
      isDirectory: false,
      sizeBytes: 1240,
      lastModified: now,
      extension: 'properties',
      content: `#Minecraft server properties
#Generated by MMSM (MrHaydenn's Minecraft Server Manager)
enable-jmx-monitoring=false
rcon.port=25575
level-seed=
gamemode=survival
enable-command-block=true
enable-query=false
generator-settings={}
enforce-secure-profile=true
level-name=world
motd=\\u00A7a${serverName} \\u00A77| \\u00A7fPowered by MMSM
query.port=${port}
pvp=true
generate-structures=true
difficulty=normal
network-compression-threshold=256
require-resource-pack=false
max-tick-time=60000
use-native-transport=true
max-players=20
online-mode=true
enable-status=true
allow-flight=false
broadcast-rcon-to-ops=true
view-distance=10
server-ip=
resource-pack-prompt=
allow-nether=true
server-port=${port}
enable-rcon=false
sync-chunk-writes=true
op-permission-level=4
prevent-proxy-connections=false
hide-online-players=false
resource-pack=
entity-broadcast-range-percentage=100
simulation-distance=8
rcon.password=
player-idle-timeout=0
force-gamemode=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
function-permission-level=2
initial-enabled-packs=vanilla
level-type=minecraft\\:normal
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
spawn-protection=16
resource-pack-sha1=
max-world-size=29999984
`,
    },
    {
      id: 'f-eula',
      name: 'eula.txt',
      path: `${root}/eula.txt`,
      isDirectory: false,
      sizeBytes: 180,
      lastModified: '2024-12-28 09:00:00',
      extension: 'txt',
      content: `#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://aka.ms/MinecraftEULA).
#Sat Dec 28 09:00:00 UTC 2024
eula=true
`,
    },
    {
      id: 'f-ops',
      name: 'ops.json',
      path: `${root}/ops.json`,
      isDirectory: false,
      sizeBytes: 310,
      lastModified: '2024-12-28 10:00:00',
      extension: 'json',
      content: `[
  {
    "uuid": "069a79f4-44e9-4726-a5be-fca90e38aaf5",
    "name": "Notch",
    "level": 4,
    "bypassesPlayerLimit": false
  },
  {
    "uuid": "853c80ef-3c37-49fd-aa49-938b674adae6",
    "name": "jeb_",
    "level": 4,
    "bypassesPlayerLimit": false
  }
]`,
    },
    {
      id: 'f-whitelist',
      name: 'whitelist.json',
      path: `${root}/whitelist.json`,
      isDirectory: false,
      sizeBytes: 240,
      lastModified: '2024-12-28 10:00:00',
      extension: 'json',
      content: `[
  {
    "uuid": "069a79f4-44e9-4726-a5be-fca90e38aaf5",
    "name": "Notch"
  },
  {
    "uuid": "853c80ef-3c37-49fd-aa49-938b674adae6",
    "name": "jeb_"
  },
  {
    "uuid": "ec561538-f3fd-461d-aff5-086364e5c52c",
    "name": "Alex"
  }
]`,
    },
    {
      id: 'f-banned-players',
      name: 'banned-players.json',
      path: `${root}/banned-players.json`,
      isDirectory: false,
      sizeBytes: 45,
      lastModified: '2024-12-28 10:00:00',
      extension: 'json',
      content: `[]`,
    },
    {
      id: 'f-banned-ips',
      name: 'banned-ips.json',
      path: `${root}/banned-ips.json`,
      isDirectory: false,
      sizeBytes: 45,
      lastModified: '2024-12-28 10:00:00',
      extension: 'json',
      content: `[]`,
    },
    {
      id: 'd-mods',
      name: 'mods',
      path: `${root}/mods`,
      isDirectory: true,
      sizeBytes: 0,
      lastModified: '2024-12-28 10:15:00',
    },
    ...modFiles,
    {
      id: 'd-config',
      name: 'config',
      path: `${root}/config`,
      isDirectory: true,
      sizeBytes: 0,
      lastModified: '2024-12-28 10:00:00',
    },
    {
      id: 'f-lithium-config',
      name: 'lithium.properties',
      path: `${root}/config/lithium.properties`,
      isDirectory: false,
      sizeBytes: 480,
      lastModified: '2024-12-28 10:05:00',
      extension: 'properties',
      content: `# Lithium Optimization Mod Configuration
# For Fabric / NeoForge
mixin.ai.pathing=true
mixin.ai.sensor=true
mixin.chunk.palette=true
mixin.entity.fast_retrieval=true
mixin.gen.fast_noise=true
mixin.world.block_entity_ticking=true
mixin.world.tick_scheduler=true
`,
    },
    {
      id: 'f-chunky-config',
      name: 'chunky.json',
      path: `${root}/config/chunky.json`,
      isDirectory: false,
      sizeBytes: 320,
      lastModified: '2024-12-28 10:08:00',
      extension: 'json',
      content: `{
  "tasks": {},
  "version": 1,
  "formatVersion": 1
}`,
    },
    {
      id: 'd-logs',
      name: 'logs',
      path: `${root}/logs`,
      isDirectory: true,
      sizeBytes: 0,
      lastModified: '2024-12-28 10:00:00',
    },
    {
      id: 'f-latest-log',
      name: 'latest.log',
      path: `${root}/logs/latest.log`,
      isDirectory: false,
      sizeBytes: 8400,
      lastModified: '2024-12-28 12:05:00',
      extension: 'log',
      content: `[12:00:00] [Server thread/INFO]: Starting Minecraft server on port ${port}
[12:00:02] [Server thread/INFO]: Loading properties from server.properties
[12:00:05] [Server thread/INFO]: Preparing level "world"
[12:00:10] [Server thread/INFO]: Done! For help, type "help"
`,
    },
    {
      id: 'd-world',
      name: 'world',
      path: `${root}/world`,
      isDirectory: true,
      sizeBytes: 0,
      lastModified: '2024-12-28 12:40:00',
    },
    {
      id: 'f-world-session',
      name: 'session.lock',
      path: `${root}/world/session.lock`,
      isDirectory: false,
      sizeBytes: 8,
      lastModified: '2024-12-28 10:00:00',
      extension: 'lock',
    },
    {
      id: 'f-world-level',
      name: 'level.dat',
      path: `${root}/world/level.dat`,
      isDirectory: false,
      sizeBytes: 14820,
      lastModified: '2024-12-28 12:45:00',
      extension: 'dat',
    },
  ];
}
