"""Deletion, compatible project selection and compact historical usage."""
import datetime
import json
import os
from pathlib import Path
import secrets
import shutil
import time
from .store import require, Problem
from .providers import MODRINTH
from urllib.parse import quote


class Maintenance:
    @staticmethod
    def dormant_status(server):
        return 'sleeping' if server['sleep'] and server.get('launch') and not server.get('manual_stop') else 'stopped'

    def recover_deletions(self):
        for row in self.store.rows('SELECT * FROM server_deletions'):
            source,target=Path(row['original']),Path(row['tombstone'])
            # Journal paths were generated by MMSM, never accepted from the API.
            require(target.parent==source.parent and target.name.startswith('.mmsm-delete-'), 'Invalid deletion journal')
            exists=self.store.rows('SELECT 1 FROM servers WHERE id=?',(row['id'],))
            if exists and target.exists():
                require(not source.exists(),'Conflicting server deletion recovery paths')
                os.replace(target,source)
            elif not exists and target.exists():
                try:shutil.rmtree(target)
                except OSError as e:
                    print('Server deletion cleanup will retry on next start:',e,flush=True)
                    continue
            self.store.execute('DELETE FROM server_deletions WHERE id=?',(row['id'],))

    def delete_server(self,sid,confirmation):
        with self.lock,self.locks[sid]:
            server=self.store.server(sid)
            require(confirmation==server['name'],'Type the exact server name to delete it')
            require(not self.alive(sid),'Stop the server before deleting it',409)
            require(sid not in self.operation_guards and sid not in self.schedule_running,'Wait for the active operation',409)
            require(self.state(sid)['status'] in ('stopped','sleeping','error','archived'),'Server is busy',409)
            source=self.folder(sid);target=source.with_name('.mmsm-delete-'+sid+'-'+secrets.token_hex(6))
            self.store.execute('INSERT INTO server_deletions VALUES(?,?,?)',(sid,str(source),str(target)))
            proxy=self.proxies.pop(sid,None)
            if proxy:proxy.close()
            moved=False
            try:
                if source.exists():os.replace(source,target);moved=True
                with self.store.lock,self.store.db:
                    db=self.store.db
                    db.execute('DELETE FROM notification_reads WHERE notification_id IN (SELECT id FROM notifications WHERE server_id=?)',(sid,))
                    for table in ('notifications','metrics','usage_hourly','backup_records'):db.execute('DELETE FROM '+table+' WHERE server_id=?',(sid,))
                    for row in db.execute('SELECT id,server_ids FROM users WHERE server_ids IS NOT NULL').fetchall():
                        db.execute('UPDATE users SET server_ids=? WHERE id=?',(json.dumps([v for v in json.loads(row['server_ids']) if v!=sid]),row['id']))
                    db.execute('DELETE FROM servers WHERE id=?',(sid,))
            except Exception:
                if moved:os.replace(target,source)
                self.store.execute('DELETE FROM server_deletions WHERE id=?',(sid,))
                if proxy and not server['archived']:self.ensure_proxy(server)
                raise
            for mapping in (self.states,self.logs,self.processes,self.online_names,self.latest['servers'],self.sampler.previous):mapping.pop(sid,None)
            try:
                if moved:shutil.rmtree(target)
                self.store.execute('DELETE FROM server_deletions WHERE id=?',(sid,))
                return {'deleted':True}
            except OSError:
                return {'deleted':True,'warning':'Server removed. Some files are locked; MMSM will retry file cleanup on its next start.'}

    def compatible_project_versions(self,sid,project_id,project_type='mod'):
        server=self.active(sid)
        require(server['loader']!='vanilla','Vanilla cannot install mods. Use Fabric, NeoForge, or Forge for mods, or Paper for plugins.',409)
        require(project_type in ('mod','plugin','modpack'),'Invalid project type')
        require(isinstance(project_id,str) and 1<=len(project_id)<=100,'Choose a Modrinth project')
        project=self.providers.get(MODRINTH+'/project/'+quote(project_id,safe=''))
        require(isinstance(project,dict) and project.get('id'),'Invalid Modrinth project response',502)
        require(project.get('server_side')!='unsupported' and project.get('environment') not in ('client_only','singleplayer_only'),'This project cannot run on a dedicated server')
        require(project.get('project_type') in (('modpack',) if project_type=='modpack' else ('mod','plugin')),'Project type does not match installer')
        versions=self.providers.mod_versions(project['id'],server)
        require(isinstance(versions,list),'Invalid Modrinth version response',502)
        result=[]
        for v in versions:
            require(isinstance(v,dict) and isinstance(v.get('id'),str) and v['id'],'Modrinth returned incomplete version details. Retry the request.',502)
            if v.get('project_id')!=project['id']:continue
            if server['minecraft'] not in v.get('game_versions',[]) or not set(self.providers.compatible_loaders(server['loader'])).intersection(v.get('loaders',[])):continue
            if v.get('environment') in ('client_only','singleplayer_only'):continue
            suffix='.mrpack' if project_type=='modpack' else '.jar'
            files=[f for f in v.get('files',[]) if f.get('filename','').endswith(suffix)]
            if not files:continue
            try:published=datetime.datetime.fromisoformat(v['date_published'].replace('Z','+00:00')).timestamp()
            except (ValueError,KeyError,TypeError):raise Problem('Modrinth returned an invalid publication date',502)
            artifact=next((f for f in files if f.get('primary')),files[0])
            label=v.get('version_number') or v.get('name') or artifact['filename'] or v['id']
            result.append({'id':v['id'],'project_id':project['id'],'name':v.get('name') or label,'version_number':label,
                           'version_type':v.get('version_type','release'),'published':published,'date_published':v['date_published'],
                           'game_versions':v['game_versions'],'loaders':v['loaders']})
        return sorted(result,key=lambda v:(v['published'],v['id']),reverse=True)

    def install_project(self,sid,data):
        with self.locks[sid]:
            self.idle(sid)
            versions=self.compatible_project_versions(sid,data.get('project_id'),data.get('type','mod'))
            require(versions,'No compatible server version is available',409)
            selected=next((v for v in versions if v['id']==data['version_id']),None) if data.get('version_id') else versions[0]
            require(selected,'This version is not compatible with the selected server')
            queued=self.install_pack(sid,selected['id']) if data.get('type')=='modpack' else self.mod_install(sid,selected['id'])
            return {**queued,'version_id':selected['id'],'version':selected['version_number']}

    def record_usage(self,sid,now,dt,metric,totals,prior):
        # Never credit manager downtime or a long paused sampling thread as play time.
        seconds=max(0,min(float(dt),10))
        players=metric.get('players')
        player_seconds=max(0,players or 0)*seconds
        rx=max(0,totals[0]-prior[0]);tx=max(0,totals[1]-prior[1])
        bucket=int(now//3600)*3600
        self.store.execute('''INSERT INTO usage_hourly VALUES(?,?,?,?,?,?,?) ON CONFLICT(server_id,bucket) DO UPDATE SET
          player_seconds=player_seconds+excluded.player_seconds,rx_bytes=rx_bytes+excluded.rx_bytes,
          tx_bytes=tx_bytes+excluded.tx_bytes,observed_seconds=observed_seconds+excluded.observed_seconds,
          peak_players=MAX(peak_players,excluded.peak_players)''',
          (sid,bucket,player_seconds,rx,tx,seconds if players is not None else 0,max(0,players or 0)))

    def usage_history(self,days=7,allowed=None,now=None):
        require(days in (7,30,90,365),'Choose 7, 30, 90 or 365 days')
        now=now or time.time();today=int(now//86400)*86400;since=today-(days-1)*86400
        servers=[s for s in self.store.servers(False) if allowed is None or s['id'] in allowed]
        ids=[s['id'] for s in servers]
        rows=self.store.rows('SELECT * FROM usage_hourly WHERE bucket>=? AND bucket<=? AND server_id IN ('+','.join('?' for _ in ids)+')',(since,now,*ids)) if ids else []
        series={since+i*86400:{'ts':since+i*86400,'player_hours':0,'rx_bytes':0,'tx_bytes':0,'observed_hours':0,'peak_players':0} for i in range(days)}
        by_server={s['id']:{'id':s['id'],'name':s['name'],'player_hours':0,'rx_bytes':0,'tx_bytes':0} for s in servers}
        for r in rows:
            day=int(r['bucket']//86400)*86400
            for dest in (series[day],by_server[r['server_id']]):
                dest['player_hours']+=r['player_seconds']/3600;dest['rx_bytes']+=r['rx_bytes'];dest['tx_bytes']+=r['tx_bytes']
            series[day]['observed_hours']+=r['observed_seconds']/3600
            series[day]['peak_players']=max(series[day]['peak_players'],r['peak_players'])
        return {'days':days,'series':list(series.values()),'servers':list(by_server.values()),'first_sample':min((r['bucket'] for r in rows),default=None),
                'totals':{k:sum(r[k] for r in by_server.values()) for k in ('player_hours','rx_bytes','tx_bytes')}}
